services:

  postgres:

    image: postgres:13

    container_name: airflow-postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    ports:
      - "5433:5432"

  airflow-init:

    image: apache/airflow:2.8.1

    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    command: >
      bash -c "
      airflow db init &&
      airflow users create
      --username admin
      --password admin
      --firstname Airflow
      --lastname Admin
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:

    image: apache/airflow:2.8.1

    restart: always

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ../ai_models:/opt/airflow/ai_models

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    command: webserver

  airflow-scheduler:

    image: apache/airflow:2.8.1

    restart: always

    depends_on:
      - airflow-webserver

    volumes:
      - ./dags:/opt/airflow/dags
      - ../ai_models:/opt/airflow/ai_models

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

    command: scheduler